version: '1.0.0'

services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    expose:
      - '6379'

  db:
    image: mysql
    environment:
      TZ: America/Brasilia
      USER: root
      PASSWORD: 123456789
      TERM: xterm-256color
    ports:
      - '3306:3306'
    expose:
      - '3306'

  web:
    build: .
    stdin_open: true
    tty: true
    entrypoint: config/setup_app.sh
    command: bash -c "rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: America/Brasilia
      TERM: xterm-256color
    env_file:
      - ./.env.development
    volumes:
      - .:/home/app/web
    ports:
      - '3000:3000'

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    env_file:
      - ./.env.development
    volumes:
      - .:/home/app/web